import os
from dotenv import load_dotenv

load_dotenv()

# Anthropic
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
EXTRACTION_MODEL = "claude-sonnet-4-6"

# ACLED credentials — register at https://acleddata.com/register/
# Auth uses OAuth2: POST email+password → 24h access token + 14-day refresh token
ACLED_EMAIL    = os.getenv("ACLED_EMAIL", "")
ACLED_PASSWORD = os.getenv("ACLED_PASSWORD", "")

# BBC RSS feeds to monitor
BBC_FEEDS = [
    "https://feeds.bbci.co.uk/news/world/rss.xml",
    "https://feeds.bbci.co.uk/news/world/africa/rss.xml",
    "https://feeds.bbci.co.uk/news/world/asia/rss.xml",
    "https://feeds.bbci.co.uk/news/world/latin_america/rss.xml",
    "https://feeds.bbci.co.uk/news/world/middle_east/rss.xml",
]

# Telegram credentials — get API ID + Hash from https://my.telegram.org
# Run python telegram_setup.py once to generate the session string
TELEGRAM_API_ID   = os.getenv("TELEGRAM_API_ID", "")
TELEGRAM_API_HASH = os.getenv("TELEGRAM_API_HASH", "")
TELEGRAM_SESSION  = os.getenv("TELEGRAM_SESSION", "")  # generated by telegram_setup.py
TELEGRAM_CHANNELS = [
    c.strip() for c in os.getenv("TELEGRAM_CHANNELS", "").split(",") if c.strip()
]

# IFRC GO — optional API token for authenticated access (richer data)
# Leave blank to use the public unauthenticated API
IFRC_GO_TOKEN = os.getenv("IFRC_GO_TOKEN", "")

# Source veracity weights (0.0 – 1.0) — used in belief aggregation
SOURCE_WEIGHTS = {
    "ifrc_go":   0.95,   # IFRC's own operational data — highest trust
    "reliefweb": 0.90,
    "gdacs":     0.90,
    "fewsnet":   0.88,
    "hdx":       0.85,
    "acled":     0.85,
    "bbc":       0.75,
    "telegram":  0.65,
    "gdelt":     0.60,
    "sitrep":    0.80,
    "email":     0.55,
    "whatsapp":  0.40,
}

# Email (IMAP) — works with any IMAP server (Gmail, Outlook, generic)
# For Gmail: enable IMAP in settings, use an App Password (not your account password)
EMAIL_IMAP_HOST = os.getenv("EMAIL_IMAP_HOST", "")
EMAIL_IMAP_PORT = int(os.getenv("EMAIL_IMAP_PORT", "993"))
EMAIL_USER      = os.getenv("EMAIL_USER", "")
EMAIL_PASSWORD  = os.getenv("EMAIL_PASSWORD", "")
EMAIL_FOLDER    = os.getenv("EMAIL_FOLDER", "INBOX")

# WhatsApp (Twilio) — sign up at https://www.twilio.com/
# Expose the dashboard with ngrok and set /webhook/whatsapp as your Twilio webhook URL
TWILIO_ACCOUNT_SID     = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN      = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_WHATSAPP_NUMBER = os.getenv("TWILIO_WHATSAPP_NUMBER", "")

# Signal recency: half-life in hours before a signal's weight decays by 50%
SIGNAL_HALFLIFE_HOURS = 48

# SQLite database path
DB_PATH = os.getenv("SENSING_DB", "sensing_agent.db")

# ReliefWeb app name (required by their API — v2 endpoint as of Nov 2025)
RELIEFWEB_APP_NAME = "Algo8-HumanitarianLogisticsAgent26-8gaxs"

# GDELT search terms — broadened to catch disaster, displacement, and access events
GDELT_QUERY = (
    "disaster OR earthquake OR flood OR cyclone OR famine OR drought "
    "OR displaced OR humanitarian OR \"food insecurity\" OR \"access constraints\""
)
GDELT_MAX_RECORDS = 20
