import asyncio
import os
import sys
from datetime import datetime, timedelta, timezone

# Graceful import — skip if telethon not installed yet
try:
    from telethon.sync import TelegramClient
    from telethon.sessions import StringSession
    _TELETHON_AVAILABLE = True
except ImportError:
    _TELETHON_AVAILABLE = False

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from config import TELEGRAM_API_ID, TELEGRAM_API_HASH, TELEGRAM_SESSION, TELEGRAM_CHANNELS

_SESSION_FILE = os.path.join(os.path.dirname(__file__), "..", "telegram.session")


def _get_client():
    """Return a TelegramClient using session string (preferred) or session file."""
    if TELEGRAM_SESSION:
        return TelegramClient(StringSession(TELEGRAM_SESSION), TELEGRAM_API_ID, TELEGRAM_API_HASH)
    return TelegramClient(_SESSION_FILE, TELEGRAM_API_ID, TELEGRAM_API_HASH)


def fetch_messages(days_back: int = 3, limit_per_channel: int = 100) -> list[dict]:
    """Fetch recent messages from configured Telegram channels.

    Requires TELEGRAM_API_ID, TELEGRAM_API_HASH, and either a TELEGRAM_SESSION
    string or a telegram.session file generated by telegram_setup.py.
    Channels are set via TELEGRAM_CHANNELS in config (comma-separated usernames).
    """
    if not _TELETHON_AVAILABLE:
        print("[telegram] telethon not installed — run: pip install telethon")
        return []

    if not TELEGRAM_API_ID or not TELEGRAM_API_HASH:
        print("[telegram] TELEGRAM_API_ID / TELEGRAM_API_HASH not set — skipping.")
        return []

    if not TELEGRAM_CHANNELS:
        print("[telegram] No channels configured in TELEGRAM_CHANNELS — skipping.")
        return []

    all_messages = []
    cutoff = datetime.now(timezone.utc) - timedelta(days=days_back)

    with _get_client() as client:
        for channel in TELEGRAM_CHANNELS:
            try:
                msgs = _fetch_channel(client, channel, cutoff, limit_per_channel)
                print(f"[telegram] @{channel}: {len(msgs)} message(s)")
                all_messages.extend(msgs)
            except Exception as e:
                print(f"[telegram] Error on @{channel}: {e}")

    return all_messages


def _fetch_channel(client, channel: str, cutoff: datetime, limit: int) -> list[dict]:
    messages = []
    for msg in client.iter_messages(channel, limit=limit):
        if not msg.text:
            continue
        msg_time = msg.date if msg.date.tzinfo else msg.date.replace(tzinfo=timezone.utc)
        if msg_time < cutoff:
            break
        messages.append({
            "source_type":   "telegram",
            "source_id":     f"{channel}_{msg.id}",
            "url":           f"https://t.me/{channel}/{msg.id}",
            "timestamp":     msg.date.isoformat(),
            "raw_text":      msg.text,
            "location_hint": {},
        })
    return messages
